before_script:
  - echo off 
  - source /etc/profile.d/rvm.sh
  - rvm use 2.2@mine
  - echo on
  #- gem install bundler
  - bundle install 
  #- bundle exec rake db:create

rspec: 
  script: "rake spec"
  tags: 
    - ~slow
  only: 
    - branches

#staging: 
#  script: "cap deploy stating"
#  type: deploy
#  tags: 
#    - capistrano
#    - debian
#  except:
#    - stable
#    - /^deploy-.*$/
